url: https://y7kim.github.io
baseurl: ''

# Site settings
title: The Dunn Lab
email: casey.dunn@yale.edu
description: "Casey Dunn's laboratory in the Department of Ecology and Evolutionary Biology at Yale University."

# Color settings (hex-codes without the leading hash-tag)
color:
  link: CBA72B
  primary: fed136
  secondary: fec503
  secondary-dark: 000

# Team names, titles and social links
people:
- name: Casey Dunn
  pic: casey
  position: Principal Investigator
  description: My CV is available <a href="/assets/Casey_Dunn_CV.pdf">here</a>.
  social:
    - title: google
      url: https://scholar.google.com/citations?user=mSMSMM4AAAAJ
    - title: github
      url: https://github.com/caseywdunn

- name: Sam Church
  pic: sam
  position: Postdoc
  description: Evo-devo, focusing on comparative methods for high-dimensional data. Phylogenetics, bioinformatics, and data viz.
  social:
    - title: github
      url: https://shchurch.github.io/

- name: Namrata Ahuja
  pic: nam
  position: Graduate Student
  description: Evo-devo of novel structures/cells and body plan formation in siphonophores. Embryology, gene expression, morphology.
  social:

- name: Dalila Destanovic
  pic: dalila
  position: Graduate Student
  description: Evolution of marine invertebrates, comparative genomics, and 3D genome organization.
  social:

- name: Dennis Pilarczyk
  pic: dennis
  position: Lab Associate
  description: Life, evolution, and everything
  social:

- name: Jasmine Mah (alum 2024)
  pic: jas
  position: Graduate Student
  description: Cell type evolution, origin and evolution of complex characters, gene-phenotype relationships.
  social:
    - title: twitter
      url: https://twitter.com/jasminelmah

- name: Lauren Mellenthin (alum 2024)
  pic: lauren
  position: Graduate Student
  description: Evolutionary origins of mesoglea and functional morphology of siphonophore nectophores.
  social:
    - title: twitter
      url: https://twitter.com/LaurMellenthin

- name: Natasha Picciani (alum 2022)
  pic: natasha
  position: Postdoc
  description: Evolution of complex traits, including vision and life stages. Phylogenetics, gene expression, morphology. <a href="https://natashapicciani.weebly.com">My site</a>.
  social:

- name: Kirstin Dion (alum 2022)
  pic: kirstin
  position: Research Assistant
  description: Genomes, animals, and populations
  social:

- name: Alex Damian Serrano (alum 2021)
  pic: alex
  position: Graduate Student
  description: Evolution and diversification of trophic niches and predatory strategies in siphonophores.
  social:
    - title: twitter
      url: https://twitter.com/antropoteuthis

- name: Reza Bergmann (alum 2021)
  pic: reza
  position: Undergraduate Student
  description: Robotics for marine natural history observations
  social:

- name: Cat Munro (alum 2018)
  pic: cat
  position: Graduate Student
  description: Evolution and development of functional specialization in siphonophores.
  social:
    - title: twitter
      url: https://twitter.com/CatMunro_
    - title: google
      url: https://scholar.google.com/citations?user=2EpYRt4AAAAJ

- name: August Guang (alum)
  pic: august
  position: Graduate Student
  description: Evolutionary processes, applied math. Phylogenetic algorithms and ßaccuracy of their results.
  social:
   - title: bitbucket
     url: https://bitbucket.org/aguang

- name: Mark Howison (alum)
  pic: mark
  position: Application Scientist
  description: As an application scientist, I help researchers better utilize high performance computing resources.
  social:
    - title: twitter
      url: https://twitter.com/markhowison
    - title: google
      url: https://scholar.google.com/citations?user=30GiMJIAAAAJ

- name: Cat Luria (alum, 2016)
  pic: luria
  position: Graduate Student
  description: Bacterial community structure in Antarctica.
  social:

- name: Zack Lewis (alum, 2020)
  pic: zack
  position: Postdoc
  description: The evolution of development, organogenesis, and gene-phenotype relationships. <a href="https://lewis.science">My site</a>.
  social:
    - title: google
      url: https://scholar.google.com/citations?user=uHN9MicAAAAJ

- name: Yuanning Li (alum, 2019)
  pic: li
  position: Postdoc
  description: Using HIV phylogenetics to better understand transmission networks.
  social:
    - title: google
      url: https://scholar.google.com/citations?user=65ygCIsAAAAJ&hl=en
    - title: twitter
      url: https://twitter.com/YuanningLi1


- name: Felipe Zapata (alum, 2016)
  pic: felipe
  position: Postdoc
  description: Phylogenetics, diversity, and computational biology. I am a botanist, but enjoy animals too. <a href="https://zapatalab.info/people/felipe.html">My site</a>.
  social:
    - title: twitter
      url: https://twitter.com/zapata_f
    - title: google
      url: https://scholar.google.com/citations?user=dwQ7qIcAAAAJ

- name: Stefan Siebert (alum, 2015)
  pic: stefan
  position: Postdoc
  description: The developmental biology and diversity of hydrozoans (Cnidaria).
  social:
    - title: google
      url: https://scholar.google.com/citations?user=G8XF6J0AAAAJ
    - title: flickr
      url: https://www.flickr.com/photos/ssiebert/

- name: Rebecca Helm (alum, 2015)
  pic: rebecca
  position: Graduate Student
  description: Evolution of development in cnidarians, as well as their systematics and natural history. My <a href="https://www.rebeccarhelm.com/">site</a>, my <a href="https://deepseanews.com/about/rr-helm/">contributions to Deep Sea News</a>.
  social:
    - title: twitter
      url: https://twitter.com/RebeccaRHelm
    - title: google
      url: https://scholar.google.com/citations?user=NYI5GP8AAAAJ

- name: Tarek Ziad (alum, 2020)
  pic: tarek
  position: Undergraduate Student
  description: Body plan development and axial patterning in Hydractinia
  social:

- name: Sam Church (alum, 2015)
  pic: sam_old
  position: Undergrad Student
  description: Comparative biology, phylogenetics, and developmental biology.
  social:

- name: Nicola Malakooti (alum, 2016)
  pic: nikka
  position: Undergraduate Student
  description: Comparative biology with additional interests in conservation. Inspired by the diversity of life.
  social:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
    - title: twitter
      url: https://twitter.com/caseywdunn
    - title: google
      url: https://scholar.google.com/citations?user=k2n_5QoAAAAJ&hl=en
    - title: bitbucket
      url: https://bitbucket.org/caseywdunn
    - title: github
      url: https://github.com/caseywdunn
    - title: vimeo-square
      url: https://vimeo.com/user1747626
    - title: flickr
      url: https://www.flickr.com/photos/12455333@N00/

# Postal address (add as many lines as necessary)
address:
  - line: 165 Prospect St.
  - line: Yale University
  - line: New Haven, CT 06511

# Build settings
markdown: kramdown
permalink: pretty
